language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: manager@mathjax.org
  on:
    tags: true
    repo: mathjax/mathjax-node-cli
  api_key:
    secure: eSOoR+JW6zwi5iPz3SCiNGEzv5EXimZ0sl+doJ1iCX5TT9VcKlBuj2HhWHoqgEJriRr6XHyvy+k0ftqW0HdoBi1BaMQIuSxx65aOrVBM4YLIYJ5ShO6h0Qu9zpGlekliDmxfal3pQweE02Pl+6I5utm9txQCQ9591e0B5Yu4ZxLslMTr9FmC34RLk9TNI6v8gUAzOuP477e1DcBqnSwIsJ9hUe1tTxOWdBPHJQX+1sgoN+SicW3s8Nc01NO3HZQse+qQfcYsxlCJrxjQzMLGro2FljmuMdD7qGI+2+NnCHyqbd8ujBDEu4Kn/h6NRofIjM0YyYcWkVskIci+CI7kyWQkfSaOunFC5IH9/jeF9Uzoi1Iy6p5KAduSlyf1+ICHL8MRk+VWf02Y2wyOVrTeldq0oZ8Utc3mxxZ9BQCWgRHYjQ5YV1vRLUQcft/vtR0BJPVd4TjgUayvpeBWTz4yUza84H9/OEfIMnIEFOt1aAt4bGDisDU6D5JfvZMfTqtSeu75zmf2es7Aeg23jfMt1Fq9+NbpC9+Yl3Vuy6FmDnv/VA9AF/OZhgmQnFsiD/Kh0AIXfK7z3XTiRYW0JljIt+ysjWY+6zV7Srmeb/DyFSfel7LsG+aqJW/j16EfG88PKM2P5hnlkxxK6TICxUkANaLOOiEduxyizzJZxffOdPM=
