language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
  secure: llMdwlUGEOzCNQHwwLCxK3hP4kc2EyXfFHwxP9FhggcIN+r1j4as13QlxlWoiPpHox2ixe5mtCC/Vc/LDo4nnfNrucPNAy5aieYKaBf954O9OxsSqG25aipAMfC3YVoUzE4EFJjaVJMTPtHFI3WIX5uW5fzgHjXUYHX20d9Z+qFtHFGHXnDGMcH9XuMKfGHwAs00z1ZkeiYnxDYuhHrBvQ0+O1FyiKw1ty6LXw6gQAbJLC8KNIjZ7jQbwejv5FRgD5imMIXH00gFtxkrgQXypdaE1lOVSN3zPFgfNVx7Cp+xv0lJUQ8Y3CfsIBYYwN5DuBz5QMrJ3h/XdC8jgxEnwNhyT/uXDl673BN2TLSdFKoewuamhjUs+YIcXW/1zvazSBX4LNsL5V9FNGveihmOeMB4aIweHioXyZf3mQg0irJByUWaY2OB/mHUxMW1yv5fWDGfPqjfmlO15gmqZUxXCzqE1JpJHm72PaqlHWNg7cdMKT4zMNfVO/bYb6/dT/U5TaDTLRxj8aIDGE9ovPPPn10fXCbt5QeqaIPXnE8cLB1YvL8hg1TztRXbEFwoNyF9UnzNpruvpXI+GnXrKek3m3sIb0fhMs0TZQ69LhSPf77ZnOJVsyEEn/g5Um0WFsvM+AgTyet+KYcrJtmcsDd//bcDRaPcZpZ6TlcQj4jkfgA=
  on:
    tags: true
    repo: mathjax/mathjax-node-cli
  API_key:
    secure: lSMG1MJpx6CdwD4msKRs68lpLt5/yuDOeYgWk9OqPOYobCxf3E2rdzOHhgnMP5vA96Go0uGueXMFHYzOqIZd5eiWyaN+Okcdw9Ry7bDX/l/8lz75c4clDF+0eh5BDrGihCZZgfnFM+BSuSRxqDf8Lk7KP8FSwUPOA59WcF///ngAfDjKJujSI9iwZITVLKvNUreTH0vT5WS1pYZXRfSvyLrlk51hAFngXd/AHmex9Aprx0LYavw2Sq32mVLNnNVu10x+x31Y2e8OWIxRP74fJ/OPiJ1afKuROXygw4uqkWGEPdeicWMQePSloae7O5xxglGpgzCQrZrdW7BmJyQpqfV/HP+RZuP4olRuxNoLw4td3z82BTdzrZiJ4v8ORw7h0pd2KcNMCb8nvD39TfJqLH9jBzMTUPuvkahy5ZVTzLDkd/spxYiP8KWVaj7Cbk9uJt3Qd5onAtf7QmZ5lpt26aVd6cekTSC5DH+y4lzpV9NWQmKuJMnLEuZyaLsr589I+pt+cNuGRqLnP0YHJ9x/zb3K1AAE4G4hXoshg4CH4Z8+hhYnqy8E5Y829B6zFUzovXUdAZqXPh7ZBzy6smvbmjNdoEXceA1OauhkCIY+d0zq+l99gw1L4/xUBd6wJB2Q+tkqeNQiraNa9JTmoUFSRPtX1ats62EgHTiThWIOeks=
